# Get the base python image
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir --prefer-binary streamlit

# Load the application code
COPY app.py /app/

# Expose the port that Streamlit runs on
EXPOSE 8501

# Set environment variable to avoid Streamlit's first-time setup prompt
ENV STREAMLIT_SERVER_HEADLESS=true
ENV STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
ENV STREAMLIT_EMAIL=""

# Command to run the application
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
